const FORMULAS = {
  linear: {
    title: "Linear",
    formula: "Y = XW^T + b",
    explanation: "线性投影，用于生成 q/k/v、MLP 中间状态或输出投影。",
    inputs: ["X", "W", "b"],
    outputs: ["Y"],
  },
  matmul: {
    title: "MatMul",
    formula: "Y = A B",
    explanation: "矩阵乘法，用于 attention score 或加权 value 聚合。",
    inputs: ["A", "B"],
    outputs: ["Y"],
  },
  softmax: {
    title: "Softmax",
    formula: "softmax(x_i) = exp(x_i) / sum_j exp(x_j)",
    explanation: "将 attention score 转成概率分布。",
    inputs: ["scores"],
    outputs: ["probabilities"],
  },
  sigmoid: {
    title: "Sigmoid",
    formula: "sigmoid(x) = 1 / (1 + exp(-x))",
    explanation: "将门控或 beta logits 映射到 0 到 1 区间。",
    inputs: ["x"],
    outputs: ["sigmoid(x)"],
  },
  split: {
    title: "Fused Projection Split",
    formula: "[q,k,v,b,f_a,g_a] = split(z; 3P,H, D,D)",
    explanation: "按 GLM-5.3-Flash checkpoint 的 fused_qkvbfg_a 投影布局拆分输出。",
    inputs: ["z", "split sizes"],
    outputs: ["q", "k", "v", "beta", "f_a", "g_a"],
  },
  causal_conv1d: {
    title: "Causal Short Convolution",
    formula: "x'_t = SiLU(Conv1D(x_{t-w+1:t}; w))",
    explanation: "GLM-5.3-Flash 对 q、k、v 使用独立 causal short convolution，并维护卷积状态。",
    inputs: ["x history", "conv weight", "conv state"],
    outputs: ["x'", "conv state"],
  },
  kda_decay: {
    title: "KDA Safe Gate Decay",
    formula: "g_t = lower_bound * sigmoid(exp(A_log) * (g_t^{raw} + dt_bias))",
    explanation: "GLM-5.3-Flash 的 bounded safe gate；A_log 和 dt_bias 是每个线性 attention head 的参数。",
    inputs: ["g_raw", "A_log", "dt_bias", "lower_bound"],
    outputs: ["decay"],
  },
  rope: {
    title: "RoPE",
    formula: "q', k' = rotate(q, k, position)",
    explanation: "对 q/k 注入旋转位置编码。",
    inputs: ["q", "k", "position"],
    outputs: ["q'", "k'"],
  },
  rmsnorm: {
    title: "RMSNorm",
    formula: "y = x / sqrt(mean(x^2) + eps) * weight",
    explanation: "按均方根归一化，不减去均值。",
    inputs: ["x", "weight", "eps"],
    outputs: ["y"],
  },
  swiglu: {
    title: "SwiGLU",
    formula: "y = SiLU(xW_gate) * (xW_up)",
    explanation: "门控前馈激活，常用于 LLM 的 MLP。",
    inputs: ["x", "W_gate", "W_up"],
    outputs: ["y"],
  },
  topk: {
    title: "TopK Routing",
    formula: "experts = topk(router_logits, k)",
    explanation: "为 token 选择得分最高的专家。",
    inputs: ["router_logits", "k"],
    outputs: ["expert_ids", "expert_weights"],
  },
  moe_dispatch: {
    title: "MoE Dispatch",
    formula: "x_e = dispatch(x, expert_ids)",
    explanation: "按路由结果把 token 分发给专家。",
    inputs: ["x", "expert_ids"],
    outputs: ["expert_inputs"],
  },
  moe_combine: {
    title: "MoE Combine",
    formula: "y = sum_e weight_e * expert_e(x_e)",
    explanation: "按路由权重合并专家输出。",
    inputs: ["expert_outputs", "expert_weights"],
    outputs: ["y"],
  },
  moe_add: {
    title: "MoE Branch Add",
    formula: "y = y_routed + y_shared",
    explanation: "Kimi-K3 将 latent routed expert 分支与 shared expert MLP 分支相加。",
    inputs: ["y_routed", "y_shared"],
    outputs: ["y"],
  },
  linear_attention: {
    title: "Gated Linear Attention",
    formula: "S_t = decay_t * S_{t-1} + k_t^T v_t; y_t = q_t S_t",
    explanation: "按 token 递推更新线性 attention 状态，避免构造完整的 query-key score 矩阵。",
    inputs: ["q", "k", "v", "decay", "state"],
    outputs: ["state", "y"],
  },
  linear_attention_gate: {
    title: "Linear Attention Output Gate",
    formula: "y_t = gate(z_t) * y_t",
    explanation: "使用门控向量调制线性 attention 输出。",
    inputs: ["z", "y"],
    outputs: ["y"],
  },
  kimi_kda: {
    title: "Kimi Delta Attention",
    formula: "beta_t=sigmoid(beta_raw_t); v'_t=beta_t(v_t-S_{t-1}k_t); S_t=exp(g_t)S_{t-1}+v'_tk_t^T; o_t=S_tq_t",
    explanation: "Kimi-K3 的 KDA chunk/recurrent 状态更新，包含 q/k L2 normalization、beta、safe decay、A_log/dt_bias 和 recurrent state。",
    inputs: ["q", "k", "v", "beta_raw", "forget_gate", "A_log", "dt_bias", "state"],
    outputs: ["state", "o"],
  },
  kimi_kda_output_gate: {
    title: "Kimi KDA Gated RMSNorm",
    formula: "y = RMSNorm(o, sigmoid(g))",
    explanation: "KDA 输出经过 gated RMSNorm 后再进入 output projection。",
    inputs: ["o", "g"],
    outputs: ["y"],
  },
  kimi_fused_qkvg_split: {
    title: "Kimi Fused QKVG Split",
    formula: "[q,k,v,g] = split(z; P,P,P,P)",
    explanation: "Kimi-K3 full-rank gate 路径把 q、k、v 和 gated RMSNorm 输入合并为一个 fused qkvg projection。",
    inputs: ["z", "projection size P"],
    outputs: ["q", "k", "v", "g"],
  },
  gated_delta_attention: {
    title: "Gated Delta Attention",
    formula: "beta_t=sigmoid(beta_raw_t); v'_t=beta_t(v_t-S_{t-1}k_t); S_t=exp(g_t)S_{t-1}+v'_tk_t^T; o_t=S_tq_t",
    explanation: "KDA 的统一 q/k L2 normalization、beta sigmoid、safe decay 和 gated-delta recurrent state 更新；模型差异记录在投影属性中。",
    inputs: ["q", "k", "v", "beta_raw", "A_log", "dt_bias", "state"],
    outputs: ["state", "o"],
  },
  gated_rmsnorm: {
    title: "Gated RMSNorm",
    formula: "y = RMSNorm(o, weight) * sigmoid(g_2)",
    explanation: "KDA recurrent attention 输出使用输入相关 gate 执行 gated RMSNorm；不同模型的 gate projection 实现记录在节点属性中。",
    inputs: ["o", "g_2", "weight"],
    outputs: ["y"],
  },
  mhc_pre: {
    title: "mHC Pre",
    formula: "p=sigmoid(M_a s_a+b_a)+eps; C=Sinkhorn(softmax(M_c s_c+b_c)+eps); x=sum_i p_i H_i",
    explanation: "vLLM MHCPreOp：从多 residual streams 计算 post mix、comb mix，并合成为 attention 输入。",
    inputs: ["residual streams", "hc function", "hc scale", "hc base"],
    outputs: ["post mix", "comb mix", "layer input"],
  },
  mhc_fused_post_pre: {
    title: "mHC Fused Post + Pre",
    formula: "(H',post',C',x') = MHCPre(MHCPost(x,H,post,C); F,scale,base)",
    explanation: "vLLM 在相邻 decoder layer 间融合上一层 post 与当前层 pre，并可同时执行 RMSNorm。",
    inputs: ["block output", "residual streams", "post mix", "comb mix", "hc function"],
    outputs: ["residual streams", "post mix", "comb mix", "layer input"],
  },
  mhc_post: {
    title: "mHC Post",
    formula: "H'_j = post_j * x + sum_i C_{ij} H_i",
    explanation: "vLLM MHCPostOp：把 attention 或 MLP 输出注入 residual streams。",
    inputs: ["block output", "residual streams", "post mix", "comb mix"],
    outputs: ["residual streams"],
  },
  mhc_contract: {
    title: "mHC Contract",
    formula: "h = (1 / n) * sum_i H_i",
    explanation: "GLM-5.3-Flash 最后一层将 n 个 residual streams 平均收缩回普通 hidden state。",
    inputs: ["residual streams"],
    outputs: ["hidden state"],
  },
  mla_query_compress: {
    title: "MLA Query Compression",
    formula: "c^q_t = W_{qa} x_t; q_t = W_{qb} RMSNorm(c^q_t)",
    explanation: "将 query 压缩到低秩 latent 后恢复多头 query。",
    inputs: ["x", "W_qa", "W_qb"],
    outputs: ["q"],
  },
  mla_kv_compress: {
    title: "MLA KV Compression",
    formula: "[c^{KV}_t, k^R_t] = W_{kv} x_t",
    explanation: "将 KV 压缩为共享 latent 与旋转位置分量，供 MLA attention 使用。",
    inputs: ["x", "W_kv"],
    outputs: ["c_KV", "k_R"],
  },
  mla_output_gate: {
    title: "MLA Output Gate",
    formula: "O' = sigmoid(W_g x) * O",
    explanation: "使用输入相关的门控向量调制 MLA 输出。",
    inputs: ["x", "W_g", "O"],
    outputs: ["O'"],
  },
  attention_residual: {
    title: "Attention Residual",
    formula: "s_i = <RMSNorm(x_i), w>; p = softmax(s); y = RMSNorm(sum_i p_i x_i)",
    explanation: "Kimi-K3 在 attention 前和 MLP 前从 snapshot bank 与当前 prefix 中按 RMSNorm 后的投影分数聚合 residual stream；block 写层额外保存新的 snapshot。",
    inputs: ["residual_states", "score_projection", "score_norm", "output_norm"],
    outputs: ["y"],
  },
  hyper_connection: {
    title: "Hyper Connection",
    formula: "h' = mix(h, block_output, injection; hc_count, lowrank)",
    explanation: "在多流 hidden state 与 attention/MLP 分支之间执行 gated residual mixing。",
    inputs: ["hidden_state", "block_output", "injection"],
    outputs: ["hidden_state", "injection"],
  },
  ple: {
    title: "Position Learning Enhancement",
    formula: "h' = h + PLE(h, input_ids, ngram_context)",
    explanation: "在指定层将 position-learning enhancement 注入多流 hidden state。",
    inputs: ["hidden_state", "input_ids", "ngram_context"],
    outputs: ["hidden_state"],
  },
  shared_expert_gate: {
    title: "Shared Expert Gate",
    formula: "y = y_routed + sigmoid(W_g x) * y_shared",
    explanation: "用输入相关 gate 调制 shared expert 输出后与 routed MoE 合并。",
    inputs: ["x", "y_routed", "y_shared", "W_g"],
    outputs: ["y"],
  },
  qsa_indexer: {
    title: "QSA Indexer",
    formula: "I = topk((W_q x) (W_k K)^T / sqrt(d_i), budget)",
    explanation: "用独立 indexer 对历史 token 打分并选择 sparse attention 的候选位置。",
    inputs: ["x", "K_cache", "W_q", "W_k", "budget"],
    outputs: ["selected_indices"],
  },
  qsa_attention: {
    title: "QSA Sparse Attention",
    formula: "O = softmax(Q K_I^T / sqrt(d)) V_I",
    explanation: "只在 QSA indexer 选择的候选位置上执行 paged sparse attention。",
    inputs: ["Q", "K_selected", "V_selected", "selected_indices"],
    outputs: ["O"],
  },
};

export function formulaForOperator(operatorId) {
  return FORMULAS[operatorId] || null;
}
